#include <iostream>
#include <vector>
using namespace std;
/**
 * ==========================================================================================================================================================
 * FUNCTION TEMPLATES: Afunction tempalte is not an actual function, but instead is a pattern for
 * what could become a function. The line containing the template declaration indicates that
 * Comparable is the template argument: It can be replaces by any type to generate a function.
 * For instance, isf a call to findMax is made with a vector<string> as parameter, then a function
 * will be generated by replacing Comparable with string.
 *
 * Basically GENERIC PROGRAMMING, LIKE TypeVar/Generic in Python.
 * ==========================================================================================================================================================
 */

/**
 * Return the maximum item in array a.
 * Assumes a.size() > 0.
 * Comparable objects must provide operator < and operator =
 */
template <typename Comparable>
const Comparable &findMax(const vector<Comparable> &a)
{
    int maxIndex = 0;

    for (int i = 1; i < a.size(); i++)
        if (a[maxIndex] < a[i])
            maxIndex = i;

    return a[maxIndex];
}

/**
 * Example from Python
 *
 * from typing import TypeVar
 *
 * T = TypeVar("T")
 * def maximum(a: T, b: T) -> T:
 *   return a if a > b else b
 *
 */
template <typename T>

T maximum(T a, T b)
{
    return a > b ? a : b;
}

/**
 * Class templates, man, just a generic class lol, let's simulate a memory cell.
 */
template <typename Object>
class MemoryCell
{

public:
    explicit MemoryCell(const Object &initValue = Object{}) : storedValue{initValue} {}

    const Object &read() const
    {
        return storedValue;
    }

    void write(const Object &x)
    {
        storedValue = x;
    }

private:
    Object storedValue;
};

int main()
{
    MemoryCell<int> m1;
    MemoryCell<string> m2{"Hello"};

    m1.write(37);
    std::cout << m1.read() << std::endl;

    m2.write(m2.read() + " World!");
    std::cout << m2.read() << std::endl;

    return 0;
}
